name = "VisualQRCP"
uuid = "a0981cf9-873b-45df-9b6b-b8d2138abab0"
authors = ["Robin Armstrong <rja243@cornell.edu>"]
version = "0.1.0"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
